version: '3'
services:
  web-front:
    image: rapidcast/web-front:latest
    build: ./
    volumes:
        - ./:/app/:delegated
    #command: streamlit run app/main.py --server.port 8501
    ports:
        - 8080:8080
